TaskTwelve.UI/Controllers/LessonsController.cs
using System.Net;
using System.Web.Mvc;
using TaskTwelve.Core.Models;
using TaskTwelve.UI.Utils;

namespace TaskTwelve.UI.Controllers
{
    public class LessonsController : Controller
    {
        private readonly DataManager _manager;

        public LessonsController()
        {
            _manager = new DataManager();
        }

        public ActionResult Index()
        {
            return View(_manager.Lessons.GetAll());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson entity = _manager.Lessons.GetById(id.Value);
            if (entity == null)
            {
                return HttpNotFound();
            }
            return View(entity);
        }

        public ActionResult Create()
        {
            ViewBag.GroupId = new SelectList(_manager.Groups.GetAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Lesson entity)
        {
            if (ModelState.IsValid)
            {
                _manager.Lessons.Add(entity);
                return RedirectToAction("Index");
            }

            ViewBag.GroupId = new SelectList(_manager.Groups.GetAll(), "Id", "Name", entity.GroupId);
            return View(entity);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson entity = _manager.Lessons.GetById(id.Value);
            if (entity == null)
            {
                return HttpNotFound();
            }

            ViewBag.GroupId = new SelectList(_manager.Groups.GetAll(), "Id", "Name", entity.GroupId);
            return View(entity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Lesson entity)
        {
            if (ModelState.IsValid)
            {
                _manager.Lessons.Edit(entity);
                return RedirectToAction("Index");
            }

            ViewBag.GroupId = new SelectList(_manager.Groups.GetAll(), "Id", "Name", entity.GroupId);
            return View(entity);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson entity = _manager.Lessons.GetById(id.Value);
            if (entity == null)
            {
                return HttpNotFound();
            }
            return View(entity);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _manager.Lessons.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _manager.Lessons.Dispose();
                _manager.Groups.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TaskTwelve.UI/Controllers/ReportsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using TaskTwelve.Core.Models;
using TaskTwelve.UI.Utils;

namespace TaskTwelve.UI.Controllers
{
    public class ReportsController : Controller
    {
        private readonly DataManager _manager;

        public ReportsController()
        {
            _manager = new DataManager();
        }

        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult StudentsByCourse()
        {
            ViewBag.CourseId = new SelectList(_manager.Courses.GetAll(), "Id", "Name");

            return View();
        }

        public ActionResult StudentsByCourseData(int? courseId)
        {
            IEnumerable<StudentNamesWithGroupReport> data = null;

            if (courseId != null)
                data = _manager.ReportsService.GetStudentsByCourse(courseId.Value);

            return PartialView("_StudentsByCourseData", data);
        }
    }
}

TaskTwelve.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("OTUS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("All lessons", "Index", "Lessons")</li>
                    <li>@Html.ActionLink("All reports", "Index", "Reports")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My TaskTwelve</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>